version: '3.7'
services:
  shecodes-backend:
    image: postgres:13
    container_name: shecodes-backend
    restart: always
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - shecodes-backend:/var/lib/postgresql/data

  shecodes-mq:
    image: rabbitmq:3-management
    container_name: 'shecodes-mq'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}
    ports:
      - ${MQ_PORT}:5672
      - ${MQ_ADMIN_PORT}:15672
    volumes:
      - shecodes-mq:/var/lib/rabbitmq

volumes:
  shecodes-backend:
    name: shecodes-backend
  shecodes-mq:
    name: shecodes-mq
