version: '3.7'
services:
  self-mood:
    image: postgres:13
    container_name: self-mood
    restart: always
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
